# Generated by Django 4.2.13 on 2026-07-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('milestones', '0001_initial'),
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_at_assessment', models.IntegerField()),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessments', to='accounts.childprofile')),
            ],
        ),
        migrations.CreateModel(
            name='RiskScore',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('green', 'Green — On Track'), ('yellow', 'Yellow — Monitor'), ('orange', 'Orange — Suggest Screening'), ('red', 'Red — Seek Evaluation')], max_length=10)),
                ('social_emotional_score', models.FloatField(default=0)),
                ('language_score', models.FloatField(default=0)),
                ('cognitive_score', models.FloatField(default=0)),
                ('gross_motor_score', models.FloatField(default=0)),
                ('fine_motor_score', models.FloatField(default=0)),
                ('behavior_score', models.FloatField(default=0)),
                ('flags_asd_pattern', models.BooleanField(default=False)),
                ('flags_adhd_pattern', models.BooleanField(default=False)),
                ('flags_dyslexia_pattern', models.BooleanField(default=False)),
                ('flags_ocd_pattern', models.BooleanField(default=False)),
                ('red_flag_triggered', models.BooleanField(default=False)),
                ('domains_with_concerns', models.JSONField(default=list)),
                ('summary_message', models.TextField(blank=True)),
                ('calculated_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='risk_score', to='assessments.assessment')),
            ],
        ),
        migrations.CreateModel(
            name='RedFlagResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_present', models.BooleanField()),
                ('parent_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='red_flag_responses', to='assessments.assessment')),
                ('red_flag', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestones.redflag')),
            ],
            options={
                'unique_together': {('assessment', 'red_flag')},
            },
        ),
        migrations.CreateModel(
            name='MilestoneResponse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('response', models.CharField(choices=[('met', 'Met'), ('emerging', 'Emerging / Sometimes'), ('not_yet', 'Not Yet'), ('concerned', 'Concerned')], max_length=10)),
                ('parent_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responses', to='assessments.assessment')),
                ('milestone_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='milestones.milestoneitem')),
            ],
            options={
                'unique_together': {('assessment', 'milestone_item')},
            },
        ),
    ]
