# Generated by Django 4.2.13 on 2026-07-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('assessments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferralGuidance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('risk_level', models.CharField(choices=[('green', 'Green'), ('yellow', 'Yellow'), ('orange', 'Orange'), ('red', 'Red')], max_length=10)),
                ('concern_tag', models.CharField(blank=True, max_length=30)),
                ('heading', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('action_items', models.JSONField(default=list)),
                ('suggested_specialists', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='AssessmentReferral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('guidance', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='referrals.referralguidance')),
                ('risk_score', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='referrals', to='assessments.riskscore')),
            ],
        ),
    ]
