# Generated by Django 4.2.13 on 2026-07-11 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MilestoneCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('domain', models.CharField(choices=[('social_emotional', 'Social & Emotional'), ('language_communication', 'Language & Communication'), ('cognitive', 'Cognitive / Early Learning'), ('gross_motor', 'Gross Motor'), ('fine_motor', 'Fine Motor & Self-Help'), ('behavior_attention', 'Behavior & Attention')], max_length=30)),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name_plural': 'Milestone Categories',
            },
        ),
        migrations.CreateModel(
            name='RedFlag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('scope', models.CharField(choices=[('global', 'Global'), ('social_communication', 'Social & Communication'), ('motor', 'Motor & Physical'), ('learning', 'Learning & School Readiness'), ('behavior', 'Emotional & Behavior')], max_length=30)),
                ('concern_tags', models.JSONField(blank=True, default=list)),
                ('applies_to_ages', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='MilestoneItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age_group', models.IntegerField(choices=[(3, 'Age 3'), (4, 'Age 4'), (5, 'Age 5'), (6, 'Age 6'), (7, 'Age 7')])),
                ('description', models.TextField()),
                ('severity_if_missed', models.CharField(choices=[('low', 'Low — monitor'), ('medium', 'Medium — recheck soon'), ('high', 'High — seek evaluation')], default='low', max_length=10)),
                ('concern_tags', models.JSONField(blank=True, default=list)),
                ('is_red_flag', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='milestones.milestonecategory')),
            ],
            options={
                'ordering': ['age_group', 'category__domain', 'order'],
            },
        ),
    ]
