# Generated by Django 4.2.13 on 2026-07-11 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('milestones', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='milestoneitem',
            name='exercise_guidance',
            field=models.TextField(blank=True, help_text='Gentle activities if milestone is missed'),
        ),
        migrations.AddField(
            model_name='milestoneitem',
            name='target_age_months',
            field=models.IntegerField(blank=True, help_text='Specific month for ages 0-2', null=True),
        ),
        migrations.AddField(
            model_name='milestoneitem',
            name='video_url',
            field=models.URLField(blank=True, help_text='Reference video for new parents', null=True),
        ),
    ]
