# Generated by Django 4.2.13 on 2026-07-11 18:13

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HandoverFolder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_group', models.CharField(blank=True, max_length=5)),
                ('physical_details', models.TextField(blank=True, help_text='Sleeping routines, physical marks, etc.')),
                ('emergency_instructions', models.TextField(blank=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('child', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='handover_folder', to='accounts.childprofile')),
            ],
        ),
        migrations.CreateModel(
            name='MedicationRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('dosage', models.CharField(max_length=50)),
                ('frequency', models.CharField(max_length=100)),
                ('instructions', models.TextField(blank=True)),
                ('folder', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='infant_care.handoverfolder')),
            ],
        ),
        migrations.CreateModel(
            name='FoodIntroduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food_name', models.CharField(max_length=100)),
                ('introduced_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('status', models.CharField(choices=[('testing', 'Testing (3-Day Buffer)'), ('safe', 'Safe / Verified'), ('reaction', 'Allergic Reaction Detected')], default='testing', max_length=20)),
                ('child', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='food_introductions', to='accounts.childprofile')),
            ],
        ),
        migrations.CreateModel(
            name='AllergySymptomLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('has_rash', models.BooleanField(default=False)),
                ('has_digestive_issues', models.BooleanField(default=False)),
                ('has_respiratory_issues', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('introduction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='symptoms', to='infant_care.foodintroduction')),
            ],
        ),
    ]
